# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sales_records.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13sales_records.proto\"\x0e\n\x0c\x45mptyMessage\"\'\n\x18PingSalesRecordsResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t2K\n\x0bSalesRecord\x12<\n\x10PingSalesRecords\x12\r.EmptyMessage\x1a\x19.PingSalesRecordsResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sales_records_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTYMESSAGE._serialized_start=23
  _EMPTYMESSAGE._serialized_end=37
  _PINGSALESRECORDSRESPONSE._serialized_start=39
  _PINGSALESRECORDSRESPONSE._serialized_end=78
  _SALESRECORD._serialized_start=80
  _SALESRECORD._serialized_end=155
# @@protoc_insertion_point(module_scope)
